name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y libnss3-dev libgconf-2-4
        google-chrome --version

    - name: Verify ChromeDriver installation
      run: |
        chromedriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: |
        Xvfb :99 &
        mvn test
      env:
        DISPLAY: :99.0
